version: "3.9"

services:
  basic-fullstack-app:
    image: basic-fullstack-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app 
      - ./backend/app/build:/app/build
    ports:
      - "8080:8080"  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  postgres_data: